name: Build

on: 
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      run: |
        wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
        # Workaround for issue https://github.com/llvm/llvm-project/issues/133861
        sudo ln -s /usr/lib/llvm-23/lib /usr/lib/lib
        sudo ln -s /usr/lib/llvm-23/include /usr/lib/include
        sudo apt-get update
        sudo apt-get install ninja-build clang-23 llvm-23-dev

    - name: Compile
      run: |
        mkdir -p build && cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j

    - name: Test
      run: |
        echo "int add(int a, int b) { return a + b; }" > test.c
        clang-23 -fpass-plugin=./cclang.so test.c -S -emit-llvm
        cat test.ll | grep -vqz "nsw"
      working-directory: build
